# Generated by Django 5.0 on 2023-12-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
