# Generated by Django 5.0 on 2023-12-12 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_email_source_alter_email_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='email',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
