# Generated by Django 5.0 on 2023-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_email_created_at_email_received_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='attachments',
        ),
        migrations.AddField(
            model_name='email',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='myapp.attachment'),
        ),
    ]
